ferdinh/defcon-z

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

A guideline for creating Issues and Pull Request.

Add Issues and Pull Request Templates

---

DEFCON Z/ProjectSettings/ProjectSettings.asset

Made updates to the project's metadata to match our latest product name and team name.

Fix unity project settings

---

DEFCON Z/Assets/Scripts/Player/CameraController.cs

Small bug effecting the height of the camera when panning fix.

Fix panning affecting height bug

---

DEFCON Z/ProjectSettings/GraphicsSettings.asset
DEFCON Z/ProjectSettings/ProjectSettings.asset
DEFCON Z/ProjectSettings/UnityConnectSettings.asset

Add build and run settings generated automatically.

Add Build Settings

---

DEFCON Z/Assets/Scripts/Entity.meta
DEFCON Z/Assets/Scripts/Entity/IDestructible.cs
DEFCON Z/Assets/Scripts/Entity/IDestructible.cs.meta
DEFCON Z/Assets/Scripts/Objects/ObjectBase.cs
DEFCON Z/Assets/Scripts/Objects/Prop.cs
DEFCON Z/Assets/Scripts/Units/UnitBase.cs

Implements interfaces rather than methods for entities.

Interface Implementation

---

DEFCON Z/Assets/Scripts/Simulation/Clock.cs
DEFCON Z/Assets/Scripts/Simulation/Clock.cs.meta

Clock represents in-game time. A "day" in a game is represented as 2 real-time seconds by default. The value is not final.

Add In-game Clock

---

DEFCON Z/Assets/Scripts/Simulation.meta
DEFCON Z/Assets/Scripts/Simulation/Modifier.cs
DEFCON Z/Assets/Scripts/Simulation/Modifier.cs.meta
DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs
DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs.meta
DEFCON Z/Assets/Scripts/Simulation/Resource.cs
DEFCON Z/Assets/Scripts/Simulation/Resource.cs.meta

This PR adds resource functionality to the game. The PR is limited to tracking the resources. The actual gathering and usage of the resources will be implemented in the next PR.
See #19, #25.

Add Resources to game

---

DEFCON Z/Assets/Scripts/Units/Human.cs
DEFCON Z/Assets/Scripts/Units/UnitBase.cs
DEFCON Z/Assets/Scripts/Units/Zombie.cs

Allows units to have initialisation code automatically run when created.
Rather than implementing unit specific methods and method calls, simplifies the process by having units implement an initialisation method for any needed code.

Implement Unit Initialisation Method

---

DEFCON Z/Assets/Prefabs/Units/Human.prefab
DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
DEFCON Z/Assets/Scenes/SimulationDevScene.unity
DEFCON Z/Assets/Scripts/GameManager.cs
DEFCON Z/Assets/Scripts/Player/InputController.cs
DEFCON Z/Assets/Scripts/Simulation/Combat.cs
DEFCON Z/Assets/Scripts/Simulation/Combat.cs.meta
DEFCON Z/Assets/Scripts/Units/UnitBase.cs
DEFCON Z/Assets/Tests/PlayMode Tests/CombatTest.cs
DEFCON Z/Assets/Tests/PlayMode Tests/CombatTest.cs.meta

Implements basic combat system.
This PR simulates combat based on in game clock tick.
In summary:
- Unit has a base health of 100.
- Unit has base attack value of 10.
- The amount of health and attack value will depend on the modifier of respective units.
In addition, the combat system uses collision to detect if two hostile unit is within range of each other to engage in combat. A RigidBody is therefore added to Human and Zombie prefab and behaves slightly different as they are harder to select.
Closes #23.
See #23.
Unit cannot attack when being released from existing fight to another one. The player must designate the unit to other clicks before engaging its new enemy.

Unit Combat

---

DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs

Modify the test by inflating the resource recovery rate by huge amount so we can reduce the amount of iteration to ensure that it reaches maximum resource.
To make the test runs faster.

Reduce Number of Iteration for Gather Resource

---

DEFCON Z/Assets/Scripts/Simulation/Resource.cs
DEFCON Z/Assets/Scripts/Units/Faction.cs
DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs

Upgrade method implementation to Fluent Design.
To make code more readable.

Implement Fluent Design to Resource

---

DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
DEFCON Z/Assets/Scripts/GameManager.cs
DEFCON Z/Assets/Scripts/Player/InGameUI.cs

Adds a purchase unit button to the in game UI

Implement Purchase Unit Button

---

DEFCON Z/Assets/Materials/Gradients.meta
DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
DEFCON Z/Assets/Scripts/Menu.meta
DEFCON Z/Assets/Scripts/Menu/UnitTestScript.meta
DEFCON Z/Assets/Scripts/Player/InGameUI.cs
DEFCON Z/Assets/Scripts/Player/SliderBar.cs
DEFCON Z/Assets/Scripts/Player/SliderBar.cs.meta

Implements the InGameUI point status display.
Closes #19

Implement Point Status Bar

---

DEFCON Z/Assets/Scripts/GameManager.cs
DEFCON Z/Assets/Scripts/Simulation/Difficulty.cs
DEFCON Z/Assets/Scripts/Simulation/Difficulty.cs.meta
DEFCON Z/Assets/Scripts/Units/Faction.cs

Add Base Difficulty implementation.
Difficulty adjust game wide modifiers.
Closes #28, closes #41
Give player an option to play the game at an easier pace or a more challenging one.

Base Game Difficulty Option

---

DEFCON Z/Assets/Tests/PlayMode Tests/LevelTest.cs
DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs

Change Test from Assert to Constraint Model (`Assert.That`)
No difference in behavior, only different assertion method.

Use Constraint Model for Test

---

DEFCON Z/Assets/Scripts/Simulation/Clock.cs

Fix 4 CodeFactor Style

---

DEFCON Z/Assets/Scripts/Player/CameraController.cs
DEFCON Z/Assets/Scripts/Player/Player.cs

Fix code styling issues for CameraController.cs and Player.cs
Closes #55, #56

Fix Code Styling Issues

---

DEFCON Z/Assets/Scripts/Entity/IDestructible.cs
DEFCON Z/Assets/Scripts/Simulation/Level.cs
DEFCON Z/Assets/Scripts/Simulation/Modifier.cs
DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs
DEFCON Z/Assets/Scripts/Units/Zombie.cs

Closes #60, #63, #64, #65, #66, #67.

Code Style Fix

---

DEFCON Z/Assets/Scripts/Player/Player.cs
DEFCON Z/Assets/Tests/PlayMode Tests/PropTests.cs
DEFCON Z/Assets/Tests/PlayMode Tests/PropTests.cs.meta
DEFCON Z/Assets/Tests/PlayMode Tests/SelectionTest.cs
DEFCON Z/Assets/Tests/PlayMode Tests/SelectionTest.cs.meta

Adds Jordans TDD unit tests, previously withheld from repo to avoid conflict.
Need to have the unit tests on the repo

Add Jordans TDD Unit Tests

---

DEFCON Z/Assets/Tests/PlayMode Tests/MainMenuTest.cs
DEFCON Z/Assets/Tests/PlayMode Tests/MainMenuTest.cs.meta

Adds Neils TDD unit tests, previously withheld from repo to avoid conflict.
Need to have the unit tests on the repo

Add Neils TDD Unit Tests 

---

DEFCON Z/Assets/Textures.meta
DEFCON Z/Logs/Packages-Update.log
DEFCON Z/Packages/manifest.json
DEFCON Z/ProjectSettings/ProjectVersion.txt
DEFCON Z/ProjectSettings/XRSettings.asset
README.md

Unity Editor version will need to be changed to 2019.1.1f1.
Closes #75 
Version 2019.1.1f1 supports the Lightweight Render Pipeline (LWRP) and shader graph, as well as numerous additions to make processes such as animations more innovative.
2019.1.1f1 also supports Data-Oriented Technology Stack (DOTS).
DOTS can take C# jobs and produces highly optim
After project conversion was completed, all tests previously created (that passed previously) passed.
The game has no obvious new issues or bugs.
No code or prefab modifications were made during the project upgrade to 2019.1.1f1

Sprint2 unity editor upgrade

---

DEFCON Z/Assets/Scripts/Units/Faction.cs
DEFCON Z/Assets/Tests/PlayMode Tests/FactionTest.cs
DEFCON Z/Assets/Tests/PlayMode Tests/FactionTest.cs.meta

This PR added new test for `Faction` class. In addition, `CanRecruitUnit` method is slightly modified to be testable.

Add Test for Faction

---

DEFCON Z/Assets/Tests/PlayMode Tests/MainMenuTest.cs

This PR updates Main Menu Tests.
It adds two test:
- Test that ensure `Panels` in main menu is setup correctly for the first time.
- Test that ensure `Panels` is toggled correctly.

Update Main Menu Tests

---

DEFCON Z/Assets/Tests/PlayMode Tests/BaseTest.cs
DEFCON Z/Assets/Tests/PlayMode Tests/BaseTest.cs.meta

A base class for tests containing a field of type GameObject.
Adding base class for test will make testing easier and less repetitive. Since our project is interacting with `MonoBehaviour` object and most of the time will require a `GameObject` to tests.

Add base test class

---

DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity

Fixes GUI scaling issues as outlined in #60 
Resolved #60.

Gui Scaling Fix

---

DEFCON Z/Assets/Tests/PlayMode Tests/MainMenuTest.cs

Removed broken main menu test, button test.
#96 
Changed implementation of quit method causing all subsequent tests after the QuitButton test to fail, as the test runner would quit.
All existing test passed as expected.

Update Menu Test

---

DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
DEFCON Z/Assets/Scripts/UI/PauseMenu.cs
DEFCON Z/Assets/Scripts/UI/PauseMenu.cs.meta

Implementation of a basic pause menu.
Need a method to pause and quit the game while playing in a level.
All existing tests pass, the game functions as expected. The menu causes no issues and doesn't break the simulation clock.

Pause Menu Initial Functionality

---

DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity

See #103.
Assign Baked Lighting to scene.

Assign Baked Lighting

---

.mergify.yml

This PR modify and create two new rules.
1. PR can now auto merge as long as there is one approved review even when there are still other reviewers that have been requested for review.
2. Add new rules that will automatically approved reviews when the state of PR changes. (e.g new commits to the branch)
3. Add new rule that automatically delete head branch after merging or closed when the label "safe to delete branch" is present.

Edit Mergify Rules

---

DEFCON Z/Assets/Scenes/GUI/Credits.txt
DEFCON Z/Assets/Scenes/GUI/Credits.txt.meta
DEFCON Z/Assets/Scenes/GUI/Menu/Credits.txt
DEFCON Z/Assets/Scenes/GUI/Menu/Credits.txt.meta
DEFCON Z/Assets/Scenes/GUI/Menu/Credits.unity
DEFCON Z/Assets/Scenes/GUI/Menu/Credits.unity.meta
DEFCON Z/Assets/Scenes/GUI/Menu/MainMenu.unity
DEFCON Z/Assets/Scripts/UI/CreditsMenu.cs
DEFCON Z/Assets/Scripts/UI/CreditsMenu.cs.meta
DEFCON Z/Assets/Scripts/UI/MainMenu.cs
DEFCON Z/ProjectSettings/EditorBuildSettings.asset

Implements credits menu.
Credits menu credits individuals who contributed throughout development of the game.
The credits menu also credits the sources of sounds and other assets used in game.
Resolves #95

Implement Credits Menu

---

DEFCON Z/Assets/Scripts/Simulation/Clock.cs

Update `Clock` Documentation

---

DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
DEFCON Z/Assets/Scripts/GameManager.cs
DEFCON Z/Assets/Scripts/UI/InGameUI.cs
DEFCON Z/Assets/Scripts/UI/PlayerUI.cs
DEFCON Z/Assets/Scripts/Units/Faction.cs

Displays player level status during game-play.
Closes #20 
As a player, I wish to be able to view the status of the current game level, so that I can plan ahead.
#20

Level Status

---

DEFCON Z/Assets/Prefabs/Units/Human.prefab
DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
DEFCON Z/Assets/Scripts/Simulation/Combat.cs
DEFCON Z/Assets/Scripts/Units/UnitBase.cs

This change adds the ability for a faction to level up by defeating enemy units.
Closes #84.
The player/faction can now strengthen and gain experience as they fight.

Enable Faction Level Up

---

DEFCON Z/Assets/Scripts/UI/PlayerUI.cs

Use the new method of `RecruitUnitAt(Vector3)` for purchase unit button.

Fix Recruit Unit Button

---

DEFCON Z/Assets/Tests/PlayMode Tests/Unit/UnitExtensionsTest.cs

This PR make the to load the necessary scene.

Fix Unit Extension Test

---

DEFCON Z/Assets/Prefabs/Units/Human.prefab
DEFCON Z/Assets/Prefabs/Units/Zombie.prefab
DEFCON Z/Assets/Scripts/Entity/Actions/IMoveable.cs
DEFCON Z/Assets/Scripts/GameManager.cs
DEFCON Z/Assets/Scripts/Simulation/AI.cs
DEFCON Z/Assets/Scripts/Simulation/AI.cs.meta
DEFCON Z/Assets/Scripts/Units/Actions/UnitMoveScript.cs
DEFCON Z/Assets/Scripts/Units/UnitBase.cs

The enemy faction can now recruit its own unit and move their unit to the Human zone.
Closes #87
So the game has more dynamic.
All existing test passes.

Implement Basic AI

---

DEFCON Z/Assets/Scripts/GameManager.cs
DEFCON Z/Assets/Scripts/Simulation/Events.cs
DEFCON Z/Assets/Scripts/Simulation/Events.cs.meta

Add a simple event where a faction gets an additional boost if they hold more than five zones.
Closes #89

Add Abundance Event

---

DEFCON Z/Assets/Scenes/GUI/InGameUI.unity
DEFCON Z/Assets/Scenes/Levels/DEFCON City/defcon city.unity
DEFCON Z/Assets/Scripts/Player/Perks.cs
DEFCON Z/Assets/Scripts/Player/Perks.cs.meta
DEFCON Z/Assets/Scripts/Player/Player.cs
DEFCON Z/Assets/Scripts/Simulation/ModifierType.cs
DEFCON Z/Assets/Scripts/Simulation/Resource.cs
DEFCON Z/Assets/Scripts/UI/PerksUI.cs
DEFCON Z/Assets/Scripts/UI/PerksUI.cs.meta
DEFCON Z/Assets/Scripts/UI/PlayerUI.cs

Implements purchasable perks for the player.
Player is able to open the perks menu to gain access to multiple purchasable perks to enhance their faction.
Resolves #85 
See #85 
Game functions normally, all existing tests pass.

Perks Additions

---

DEFCON Z/Assets/Tests/PlayMode Tests/ResourceTest.cs

Update the Max Resource Point tests to reflect the new formula used.
See #85 and #135 .

Update Max Point Test

---

DEFCON Z/Assets/Scripts/Units/UnitBase.cs

To ensure there is no null reference exception when there is problem in loading the audio.

Add Null Check for Combat Audio
